#!/usr/bin/busybox sh

shell()
{
    sleep 3
    echo 0 > /proc/sys/kernel/printk

    echo "Dropping into shell"
    HOME=/root
    $1 setsid cttyhack sh -l
}

find()
{
    local n=${1%%=*} p=${1#*=}

    for i in $(seq 1 10); do
        findfs $p && break
        sleep 1
    done
}

####################
/usr/bin/busybox --install

mount -n -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -n -t devpts   devpts   /dev/pts
mount -n -t proc     proc     /proc
mount -n -t sysfs    sysfs    /sys

init=/sbin/init

overlay=
resume=
root=
rootdir=/mnt/root

for cmd in $(cat /proc/cmdline); do
    case ${cmd} in
        init=*)    init=${cmd#init=};;
        overlay)   overlay=y;;
        resume=*)  resume=$(find $cmd);;
        root=*)    root=$(find $cmd);;
        shell)     shell;;
    esac
done

if [ -n "$resume" -a -e /sys/power/resume ]; then
    # echo device major and minor numbers in the form x:y
    min=$(stat -c %t $resume)
    maj=$(stat -c %T $resume)
    echo "$((0x$min)):$((0x$maj))" > /sys/power/resume
fi

mount_root()
{(
    set -e
    mount -n -o ro $root $rootdir

    if [ -n "$overlay" ]; then
        mkdir /mnt/root-ro
        mount --move  $rootdir /mnt/root-ro

        mkdir /mnt/root-rw
        mount -t tmpfs root-rw /mnt/root-rw

        mkdir /mnt/root-rw/upperdir /mnt/root-rw/workdir
        mount -n -t overlay -o lowerdir=/mnt/root-ro,upperdir=/mnt/root-rw/upperdir,workdir=/mnt/root-rw/workdir overlay $rootdir

        mkdir $rootdir/mnt/root-ro $rootdir/mnt/root-rw
        mount --move  /mnt/root-ro $rootdir/mnt/root-ro
        mount --move  /mnt/root-rw $rootdir/mnt/root-rw
    fi
)}

if [ -n "$root" ]; then
    if mount_root; then
        umount -n /sys
        umount -n /proc
        umount -n /dev/pts
        umount -n /dev
        exec switch_root $rootdir $init
    fi
    echo "Failed to switch root"
else
    echo "Root device not found"
fi

shell exec
