#!/bin/bash

source colors
(($EUID == 0)) || die "Must be root"

systemd-nspawn --bind=/var/cache/apt/archives --resolv-conf=bind-stub --directory=root/ --timezone=off "$@"
rm -rv root/{root,home/*}/.bash_history 2>/dev/null
