#!/bin/bash

if (($EUID != 0)); then
    echo "Must be root"
    exit 1
fi

systemd-nspawn --bind=/var/cache/apt/archives --resolv-conf=bind-stub --directory=root/ --timezone=off "$@"
rm -rv root/{root,home/*}/.bash_history 2>/dev/null
