#!/bin/bash
set -e

source colors
(($EUID == 0)) || die "Must be root"

# create bootable USB
(($# == 1)) && target="$1" || die "Missing target path"

cyan "Creating grub.cfg"
mkdir -p "$target/grub"
cat > "$target/grub/grub.cfg" <<EOF
# grub.cfg

insmod part_gpt
insmod ext2

set gfxmode=auto
set gfxpayload=keep
insmod all_video
insmod gfxterm

menuentry "Boot into install shell" {
    echo "Loading kernel"
    linux /boot/vmlinuz shell

    echo "Loading initrd"
    initrd /boot/initrd.img

    echo "Booting"
}

menuentry "Boot from HDD" {
    echo "Loading kernel"
    linux /boot/vmlinuz root=LABEL=root ro net.ifnames=0

    echo "Loading initrd"
    initrd  /boot/initrd.img

    echo "Booting"
}
EOF

cyan "Installing GRUB"
mkdir -p "$target/EFI"
grub-install -v --boot-directory="$target" --efi-directory="$target" --removable --target=i386-efi
grub-install -v --boot-directory="$target" --efi-directory="$target" --removable --target=x86_64-efi

cyan "Copying Linux kernel"
mkdir -p "$target/boot"
cp -Lv /boot/vmlinuz "$target/boot/"

cyan "Creating initrd"
mkinitramfs -d initramfs-tools -o "$target/boot/initrd.img"
