#!/bin/bash

if (($# != 1)); then
    echo "Usage: $0 <drive>"
    exit 1
fi

run() { echo "* $@"; "$@"; echo; }

run parted $1 mktable gpt
run parted $1 mkpart efi 0% 512MiB
run parted $1 set 1 boot on
run parted $1 mkpart root 512MiB 100%

run mkfs.fat -F 32 -n efi ${1}1
run mkfs.ext4 -L root ${1}2
