#!/bin/sh
set -e

omount()
{
    if ! grep -q " $2 " /proc/mounts; then
        mount -t $1 $1 $2
    fi
}

cage=$(readlink -f ${1:-.})

omount sysfs    $cage/sys
omount proc     $cage/proc
omount devtmpfs $cage/dev
omount devpts   $cage/dev/pts

if grep -q efivarfs /proc/filesystems; then
    omount efivarfs $cage/sys/firmware/efi/efivars
fi
