#!/bin/sh

oumount()
{
    if grep -q " $1 " /proc/mounts; then
        umount $1
    fi
}

cage=$(readlink -f ${1:-.})

oumount $cage/sys/firmware/efi/efivars
oumount $cage/dev/pts
oumount $cage/dev
oumount $cage/proc
oumount $cage/sys
