#!/bin/sh

if [ $# -ne 1 ]; then
    echo "Usage: $0 <drive>"
    exit 1
fi

echo -n $1 | tail -c1 | grep -q "[0-9]" && p=${1}p || p=$1

parted $1 mktable gpt
parted $1 mkpart efi 0% 512MiB
parted $1 set 1 boot on
parted $1 mkpart root 512MiB 100%

mkfs.fat -F 32 -n efi ${p}1
mkfs.ext4 -L root ${p}2
