#!/bin/sh

if [ "$1" = "prereqs" ]; then
    echo ""
    exit 0
fi

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/busybox /usr/bin/busybox.full
copy_exec /usr/bin/mount
copy_exec /usr/bin/tar
copy_exec /usr/sbin/mkfs.ext4
copy_exec /usr/sbin/mkfs.fat
copy_exec /usr/sbin/mkfs.ntfs
copy_exec /usr/sbin/parted

copy_exec initrd/usr/sbin/cmount /usr/sbin
copy_exec initrd/usr/sbin/cumount /usr/sbin
copy_exec initrd/usr/sbin/part_bios /usr/sbin
copy_exec initrd/usr/sbin/part_efi /usr/sbin

copy_file conf initrd/etc/profile /etc
