#!/bin/sh

if [ "$1" == "prereqs" ]; then
    echo ""
    exit 0
fi

grep -qE " shell( |$)" /proc/cmdline || exit 0

# replace busybox with full version
find -samefile /usr/bin/busybox -exec rm '{}' ';'
mv /usr/bin/busybox.full /usr/bin/busybox
/usr/bin/busybox --install

echo "Dropping into shell"
hostname linux
export PS1='\u@\h:\w\p '
exec setsid cttyhack sh -l
