#!/bin/sh

if [ "$1" = "prereqs" ]; then
    echo ""
    exit 0
fi

grep -qE " shell( |$)" /proc/cmdline || exit 0

# replace busybox with full version
find -samefile /usr/bin/busybox -exec rm '{}' ';'
mv /usr/bin/busybox.full /usr/bin/busybox
/usr/bin/busybox --install

sleep 3
echo "Dropping into shell"
exec setsid cttyhack sh -l
