#!/bin/sh

PREREQ=""
prereqs() { echo "$PREREQ"; }

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

if grep -qE " shell( |$)" /proc/cmdline; then
    cat >> $HOME/.profile <<EOF
alias ll="ls -lF"
alias la="ls -laF"
EOF

    export PS1="root@linux:# "
    while :; do /bin/sh -l; done
fi

exit 0
